### PR TITLE
scaled the splash windows

### PR DESCRIPTION
**Pull request by notnorandxnor**
For larger monitors/TVs, depending on your scaling settings, you may need to scale the splash window dimensions or the text will be truncated

### CODE REVIEW

**Comment by 2called-chaos** [comment]
Thank  you :) Could you remove the .bak file from the PR? Then I can merge without edit

**Comment by notnorandxnor** [comment]
done!

**Comment by 2called-chaos** [comment]
I applied a few fixes and changed the default to 1, remember to set this back to 3 in your config.ahk (you can set it now and then it keeps working when you update)

And thanks again for your contribution.

**Comment by notnorandxnor** [comment]
A pleasure, and thanks for developing this script and making it available.

**Pull request merged**
